services:
  caddy:
    image: ghcr.io/0xf00f00/caddy-proxy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTIFICATE_EMAIL=${CERTIFICATE_EMAIL}
      - WEB_DOMAINS=${WEB_DOMAINS}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - PROXY_USER=${HTTPS_PROXY_USER}
      - PROXY_PASSWORD=${HTTPS_PROXY_PASSWORD}
      - PROXY_REJECT_IPS=${HTTPS_PROXY_REJECT_IPS}
      - PROXY_REJECT_DOMAINS=${HTTPS_PROXY_REJECT_DOMAINS}
      - XRAY_PATH=${XRAY_PATH}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - decoy
      - naive
      - xray

  # Sing-box naive INBOUND
  naive:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: naive
    restart: unless-stopped
    environment:
      - PROXY_USER=${HTTPS_PROXY_USER}
      - PROXY_PASSWORD=${HTTPS_PROXY_PASSWORD}
    volumes:
      - ./naive/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  # Xray INBOUND (VLESS over ws + xhttp)
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    environment:
      - XRAY_UUID=${XRAY_UUID}
      - XRAY_PATH=${XRAY_PATH}
    volumes:
      - ./xray/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  decoy:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    container_name: decoy
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: